# Generated by Django 4.0.6 on 2022-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='age',
            field=models.FloatField(),
        ),
    ]
