# Generated by Django 4.0.6 on 2022-07-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0003_remove_familyinfo_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinfo',
            name='name',
        ),
    ]
