# Generated by Django 4.0.6 on 2022-07-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0004_remove_familyinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('Cumpleaños', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyInfo',
        ),
    ]
