# Generated by Django 4.0.6 on 2022-07-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0005_info_delete_familyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Cumpleaños',
        ),
    ]
